import { Course } from './course.model';

export const COURSES_MOCK: Course[] = [
  {
    id: 'c1',
    title: 'Základy Angular Signals',
    category: 'kurz',
    description:
      'Úvodní kurz pro vývojáře, kteří chtějí zvládnout reaktivitu v Angularu bez RxJS — signály, computed a effect na praktických příkladech.',
    dateStart: '2026-09-15',
    location: 'Praha, coworking Vzlet',
    instructor: 'Jana Nováková',
    price: 3200,
    capacityTotal: 16,
    capacityRegistered: 11,
    registrationDeadline: '2026-09-08',
    requiresMembership: false,
    minAge: 18,
    requiredQualification: null,
  },
  {
    id: 'c2',
    title: 'Workshop: Tailwind pro produkci',
    category: 'seminar',
    description:
      'Půldenní workshop o škálování Tailwind CSS ve velkých projektech — design tokeny, konfigurace, výkon a spolupráce s designérem.',
    dateStart: '2026-09-22',
    location: 'Brno, Impact Hub',
    instructor: 'Tomáš Král',
    price: 1800,
    capacityTotal: 20,
    capacityRegistered: 20,
    registrationDeadline: '2026-09-15',
    requiresMembership: false,
    minAge: 16,
    requiredQualification: null,
  },
  {
    id: 'c3',
    title: 'Zkouška: Senior Frontend Developer',
    category: 'zkouska',
    description:
      'Certifikační zkouška ověřující pokročilé znalosti moderního frontendu — architektura komponent, výkon, testování a přístupnost.',
    dateStart: '2026-10-05',
    location: 'Praha, online',
    instructor: 'Michal Beneš',
    price: 4500,
    capacityTotal: 10,
    capacityRegistered: 4,
    registrationDeadline: '2026-09-28',
    requiresMembership: true,
    minAge: 21,
    requiredQualification: 'Certifikace Frontend Developer (základní úroveň)',
  },
  {
    id: 'c4',
    title: 'Accessibility základy',
    category: 'seminar',
    description:
      'Praktický seminář o přístupnosti webových aplikací — WCAG, ARIA role, testování se čtečkou obrazovky a časté chyby ve formulářích.',
    dateStart: '2026-10-12',
    location: 'Ostrava, TechHub',
    instructor: 'Klára Horáková',
    price: 1500,
    capacityTotal: 24,
    capacityRegistered: 9,
    registrationDeadline: '2026-10-05',
    requiresMembership: false,
    minAge: 16,
    requiredQualification: null,
  },
  {
    id: 'c5',
    title: 'TypeScript pro pokročilé',
    category: 'kurz',
    description:
      'Dvoudenní kurz zaměřený na pokročilé typové konstrukce — generika, podmíněné typy, mapované typy a typová bezpečnost API.',
    dateStart: '2026-10-20',
    location: 'Praha, coworking Vzlet',
    instructor: 'David Procházka',
    price: 5400,
    capacityTotal: 14,
    capacityRegistered: 6,
    registrationDeadline: '2026-10-13',
    requiresMembership: false,
    minAge: 18,
    requiredQualification: null,
  },
  {
    id: 'c6',
    title: 'Zkouška: Angular Architect',
    category: 'zkouska',
    description:
      'Náročná certifikační zkouška pro architekty frontendových systémů — modulární architektura, výkon ve velkém měřítku a code review.',
    dateStart: '2026-11-02',
    location: 'Praha, online',
    instructor: 'Michal Beneš',
    price: 6200,
    capacityTotal: 8,
    capacityRegistered: 8,
    registrationDeadline: '2026-10-26',
    requiresMembership: true,
    minAge: 21,
    requiredQualification: 'Certifikace Senior Frontend Developer',
  },
  {
    id: 'c7',
    title: 'Design systémy v praxi',
    category: 'kurz',
    description:
      'Kurz o budování a údržbě design systémů — komponentové knihovny, tokeny, dokumentace a spolupráce mezi designem a vývojem.',
    dateStart: '2026-11-09',
    location: 'Brno, Impact Hub',
    instructor: 'Barbora Svobodová',
    price: 3900,
    capacityTotal: 18,
    capacityRegistered: 5,
    registrationDeadline: '2026-11-02',
    requiresMembership: false,
    minAge: 18,
    requiredQualification: null,
  },
];
