import { Course } from './course.model';

export const COURSES_MOCK: Course[] = [
  {
    id: 'c1',
    title: 'Základy lezení na umělé stěně',
    category: 'kurz',
    description:
      'Úvodní kurz pro začátečníky bez zkušeností — jistící techniky, vázání uzlů, bezpečnost na stěně a základy pohybu na skalách.',
    dateStart: '2026-09-15',
    location: 'Praha, lezecká stěna Smíchoff',
    instructor: 'Jana Nováková',
    price: 3200,
    capacityTotal: 16,
    capacityRegistered: 11,
    registrationDeadline: '2026-09-08',
    requiresMembership: false,
    requiresAdult: false,
    requiresQualification: false,
  },
  {
    id: 'c2',
    title: 'Workshop: Lezení na vícedélkových cestách',
    category: 'seminar',
    description:
      'Celodenní workshop zaměřený na taktiku a bezpečnost na vícedélkových skalních cestách — budování stanovišť, slaňování a rychlá výměna vedení.',
    dateStart: '2026-09-22',
    location: 'Adršpach, cvičná skála',
    instructor: 'Tomáš Král',
    price: 1800,
    capacityTotal: 20,
    capacityRegistered: 20,
    registrationDeadline: '2026-09-15',
    requiresMembership: false,
    requiresAdult: false,
    requiresQualification: true,
  },
  {
    id: 'c3',
    title: 'Zkouška: Cvičitel lezení na umělých stěnách',
    category: 'zkouska',
    description:
      'Certifikační zkouška ověřující odborné znalosti a praktické dovednosti pro vedení lezeckých kurzů — metodika výuky, jištění a první pomoc.',
    dateStart: '2026-10-05',
    location: 'Praha, lezecká stěna Smíchoff',
    instructor: 'Michal Beneš',
    price: 4500,
    capacityTotal: 10,
    capacityRegistered: 4,
    registrationDeadline: '2026-09-28',
    requiresMembership: true,
    requiresAdult: true,
    requiresQualification: true,
  },
  {
    id: 'c4',
    title: 'Bezpečnost v horách základy',
    category: 'seminar',
    description:
      'Praktický seminář o pohybu v horském terénu — čtení počasí, lavinové riziko, orientace bez signálu a řešení nouzových situací.',
    dateStart: '2026-10-12',
    location: 'Krkonoše, horská chata Labská bouda',
    instructor: 'Klára Horáková',
    price: 1500,
    capacityTotal: 24,
    capacityRegistered: 9,
    registrationDeadline: '2026-10-05',
    requiresMembership: false,
    requiresAdult: false,
    requiresQualification: false,
  },
  {
    id: 'c5',
    title: 'Skialpinismus pro pokročilé',
    category: 'kurz',
    description:
      'Dvoudenní kurz zaměřený na pokročilou techniku skialpového výstupu a sjezdu — stoupací stopa, lavinová prevence a záchrana ve výslužné vrstvě.',
    dateStart: '2026-10-20',
    location: 'Krkonoše, Labský důl',
    instructor: 'David Procházka',
    price: 5400,
    capacityTotal: 14,
    capacityRegistered: 6,
    registrationDeadline: '2026-10-13',
    requiresMembership: false,
    requiresAdult: true,
    requiresQualification: true,
  },
  {
    id: 'c6',
    title: 'Zkouška: Horský vůdce',
    category: 'zkouska',
    description:
      'Náročná certifikační zkouška pro vedení horských expedic — alpská technika, záchranné postupy, orientace a vedení skupiny v exponovaném terénu.',
    dateStart: '2026-11-02',
    location: 'Vysoké Tatry, horská chata Téryho',
    instructor: 'Michal Beneš',
    price: 6200,
    capacityTotal: 8,
    capacityRegistered: 8,
    registrationDeadline: '2026-10-26',
    requiresMembership: true,
    requiresAdult: true,
    requiresQualification: true,
  },
  {
    id: 'c7',
    title: 'Skalní lezení v praxi',
    category: 'kurz',
    description:
      'Kurz o přechodu ze stěny na skálu — čtení cest, výběr jištění, budování stanovišť a etika lezení v přírodních oblastech.',
    dateStart: '2026-11-09',
    location: 'Český ráj, Hrubá Skála',
    instructor: 'Barbora Svobodová',
    price: 3900,
    capacityTotal: 18,
    capacityRegistered: 5,
    registrationDeadline: '2026-11-02',
    requiresMembership: false,
    requiresAdult: false,
    requiresQualification: false,
  },
];
